spring:
  application:
    name: nine-template-backend
  datasource:
    url:
    username:
    password:

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.apache.ibatis: DEBUG

server:
  port: 8080
  forward-headers-strategy: native

app:
  log:
    path:
    name: nine-template

nine:
  ai:
    gemini:
      api-key:
      default-model: gemini-2.5-flash
  stream:
    max-concurrent: 10 # 동시 접속 제한 수
    enabled: true
