spring:
  application:
    name: nine-template-backend
  datasource:
    url:
    username:
    password:

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    jdbc:
      sqltiming: INFO
      sqlonly: DEBUG

server:
  port: 8080
  forward-headers-strategy: native

nine:
  ai:
    gemini:
      api-key:
